spring:
  profiles:
    active: peer2

---
server:
  port: 8761
spring:
  profiles: peer1
  application:
    name: peer1
eureka:
  instance:
    hostname: peer1
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://peer2:8769/eureka/

---
server:
  port: 8769
spring:
  profiles: peer2
  application:
    name: peer2
eureka:
  instance:
    hostname: peer2
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/